version: 2.1
jobs:
  checkout:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive
      - persist_to_workspace:
          root: "."
          paths:
            - "*"
  test:
    docker:
      - image: altosi/unity-test:0.0.1
    steps:
      - attach_workspace:
          at: "."
      - run:
          name: "Run tests"
          command: bin/run-tests.sh
  build:
    docker:
      - image: altosi/esp8266-build:0.0.1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - attach_workspace:
          at: "."
      - run:
          name: "Build firmware"
          command: bin/build-debug-firmware.sh
      - store_artifacts:
          path: build-debug/firmware/firmware.elf
          destination: firmware.elf
workflows:
  build:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - build:
          requires:
            - test
